import { FormEvent, useState } from 'react'
import { DictionaryResult, DictionaryResultCard } from './DictionaryResultCard'

export function DictionaryPage({ onLookup, onPlay, onMarkUnknown, onOpenUnknownItems, voices = [] }: { onLookup: (request: { text: string; source_language: 'auto' | 'en' | 'zh' }) => Promise<DictionaryResult>; onPlay?: (entryId: string, voiceVersionId?: string, regenerate?: boolean) => Promise<void> | void; onMarkUnknown: (entryId: string) => Promise<void> | void; onOpenUnknownItems?: () => void; voices?: Array<{ id: string; display_name: string }> }) {
  const [text, setText] = useState(''); const [direction, setDirection] = useState<'auto' | 'en' | 'zh'>('auto'); const [result, setResult] = useState<DictionaryResult | null>(null); const [message, setMessage] = useState(''); const [voiceVersionId, setVoiceVersionId] = useState(''); const [audioBusy, setAudioBusy] = useState(false)
  const lookup = async (event: FormEvent) => { event.preventDefault(); if (!text.trim()) return; try { setResult(await onLookup({ text: text.trim(), source_language: direction })); setMessage('') } catch { setMessage('查询失败，请检查 AI 配置后重试。') } }
  const play = async (regenerate = false) => { if (!result || !onPlay || audioBusy) return; setAudioBusy(true); try { if (regenerate) await onPlay(result.entry_id, voiceVersionId || undefined, true); else await onPlay(result.entry_id, voiceVersionId || undefined); setMessage(regenerate ? '新发音已生成并播放。' : '正在播放发音。') } catch { setMessage(regenerate ? '重新生成失败，原发音仍可继续使用。' : '播放失败，请检查英语发音服务配置。') } finally { setAudioBusy(false) } }
  return <section className="dictionary-page"><header><h1>辞典</h1><p>支持单词、短语和完整句子。</p>{onOpenUnknownItems && <button className="dictionary-unknown-link" onClick={onOpenUnknownItems}>查看生词本</button>}</header><form onSubmit={event => void lookup(event)}><label>翻译方向<select aria-label="翻译方向" value={direction} onChange={event => setDirection(event.target.value as typeof direction)}><option value="auto">自动</option><option value="en">英译中</option><option value="zh">中译英</option></select></label><label>查询内容<textarea value={text} maxLength={2000} onChange={event => setText(event.target.value)} placeholder="输入单词、短语或句子" /></label><button type="submit">查询</button></form>{result && <label className="dictionary-voice">朗读声音<select aria-label="朗读声音" value={voiceVersionId} onChange={event => setVoiceVersionId(event.target.value)}><option value="">使用设置中的英语发音</option>{voices.map(voice => <option key={voice.id} value={voice.id}>{voice.display_name}</option>)}</select></label>}{message && <p role="status">{message}</p>}{result && <DictionaryResultCard result={result} audioBusy={audioBusy} onPlay={onPlay ? () => void play() : undefined} onRegenerate={onPlay ? () => void play(true) : undefined} onMarkUnknown={entryId => void onMarkUnknown(entryId)} />}</section>
}
